twilio:
  account_sid: XXXXXXXX
  auth_token: XXXXXXX
  trial_number: XXXXXXX

spring:
  jpa:
    database-platform: XXXXXXX
  datasource:
    url: XXXXXXX
    username: XXXXXXX
    password: XXXXXXX
logging.level.com.project.smstodo.sms: DEBUG



